/**
 * Reference imagery for the marketing page.
 *
 * The landing page used to illustrate itself with six animated SVG gradients
 * bundled under public/samples. They were honest — obviously not photographs —
 * but they made a product that renders images look like it could not render
 * one. These are real photographs, served from Unsplash's CDN.
 *
 * What they are NOT is model output. Nothing in here was generated by this app,
 * and every surface that uses it says so: the showcase carries a badge and a
 * sentence, because a stock photograph captioned "Made with Kinetic" would be a
 * straightforward lie, and a prettier one than the gradients ever told.
 *
 * The real feed wins wherever it exists. `CreatorShowcase` prefers published
 * work and falls back to this only when nothing has been published yet.
 *
 * ## Why ids rather than an API call
 *
 * Unsplash's search API needs a registered Access Key, and its website refuses
 * scrapers (401). A curated set of CDN ids needs no key, no network call at
 * render time and no runtime dependency on a third party staying up. The cost
 * is that this list is hand-maintained — which is why every id below was
 * verified to resolve and every photograph was actually looked at before it was
 * described. The `alt` text says what is really in the frame.
 *
 * Licence: the Unsplash licence permits free commercial and non-commercial use
 * without permission. Attribution is not required but is appreciated, which is
 * why the showcase section carries a credit line.
 */

export interface StockPhoto {
  /** Unsplash CDN photo id, e.g. `photo-1506905925346-21bda4d32df4`. */
  id: string
  /** What the photograph actually shows. Written from looking at it. */
  alt: string
}

/**
 * The curated set.
 *
 * Landscape and atmosphere on purpose: they read as frames from something,
 * which is the job, and they contain no recognisable faces — a stock portrait
 * beside the words "Made with Kinetic" would imply a person consented to being
 * an example of this product's output.
 */
export const STOCK = {
  alpineCloud: {
    id: 'photo-1506905925346-21bda4d32df4',
    alt: 'Snow-covered peaks rising above a sea of cloud at sunset',
  },
  mistCliffs: {
    id: 'photo-1470071459604-3b5ec3a7fe05',
    alt: 'Green cliffs under low mist, sun breaking through heavy cloud',
  },
  forestPath: {
    id: 'photo-1441974231531-c6227db76b6e',
    alt: 'A path receding into a forest, warm light between the trunks',
  },
  lakeReflection: {
    id: 'photo-1493246507139-91e8fad9978e',
    alt: 'Turquoise mountain lake mirroring peaks lit by alpenglow',
  },
  oceanDusk: {
    id: 'photo-1518837695005-2083093ee35b',
    alt: 'The surface of the sea at dusk, shallow depth of field',
  },
  breakingWave: {
    id: 'photo-1500375592092-40eb2168fd21',
    alt: 'A wave breaking in close-up, backlit by low golden sun',
  },
  footbridge: {
    id: 'photo-1447752875215-b2761acb3c5d',
    alt: 'A narrow footbridge leading straight into dense forest',
  },
  valleyHaze: {
    id: 'photo-1506744038136-46273834b3fb',
    alt: 'A wide river valley between granite walls in dawn haze',
  },
  nightSky: {
    id: 'photo-1519681393784-d120267933ba',
    alt: 'The Milky Way and a shooting star over snow-covered mountains',
  },
  stageLights: {
    id: 'photo-1492684223066-81342ee5ff30',
    alt: 'Confetti falling through coloured stage light above a crowd',
  },
} as const satisfies Record<string, StockPhoto>

export type StockKey = keyof typeof STOCK

/** Pixel dimensions per aspect ratio, at a width that suits a card. */
const SIZES: Record<string, { width: number; height: number }> = {
  '16:9': { width: 1200, height: 675 },
  '9:16': { width: 720, height: 1280 },
  '1:1': { width: 900, height: 900 },
  '4:5': { width: 900, height: 1125 },
  '21:9': { width: 1400, height: 600 },
}

/**
 * A CDN URL for one photograph at one aspect ratio.
 *
 * Unsplash crops and re-encodes on their side from these query parameters, so
 * any photograph can serve any ratio and the browser is never sent more pixels
 * than the card will use. `auto=format` hands WebP to browsers that take it.
 */
export function stockUrl(photo: StockPhoto, ratio = '16:9'): string {
  const { width, height } = SIZES[ratio] ?? SIZES['16:9']!

  return `https://images.unsplash.com/${photo.id}?auto=format&fit=crop&w=${width}&h=${height}&q=75`
}

/** Where the credit line points. */
export const UNSPLASH_CREDIT_URL = 'https://unsplash.com'

const STOCK_KEYS = Object.keys(STOCK) as StockKey[]

/**
 * A stable photograph for an arbitrary key.
 *
 * Deterministic, so a preset shows the same frame on every render, on the
 * server and the client, and the grid does not reshuffle when a page
 * revalidates. FNV-1a because it is four lines and the distribution over
 * thirty-six slugs is good enough for picking a picture.
 */
export function stockFor(seed: string, ratio = '16:9'): string {
  let hash = 2166136261
  for (let i = 0; i < seed.length; i += 1) {
    hash ^= seed.charCodeAt(i)
    hash = Math.imul(hash, 16777619)
  }

  const key = STOCK_KEYS[Math.abs(hash) % STOCK_KEYS.length]!
  return stockUrl(STOCK[key], ratio)
}

/** True for the animated SVG placeholders bundled under public/samples. */
export function isBundledPlaceholder(url: string | null | undefined): boolean {
  return Boolean(url?.startsWith('/samples/'))
}
